package com.d.music.data.database.greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "CUSTOM_LIST_MODEL".
 */
public class CustomListModel {

    public Long id;
    public String name;
    public Long count;
    public Integer seq;
    public Integer sortType;
    public Integer pointer;

    /**
     * Extra: Not in the database
     */
    // 附加属性：是否选中
    public boolean exIsChecked = false;
    // 附加属性：是否滑动打开
    public boolean exIsOpen = false;

    public CustomListModel() {
    }

    public CustomListModel(Long id) {
        this.id = id;
    }

    public CustomListModel(Long id, String name, Long count, Integer seq, Integer sortType, Integer pointer) {
        this.id = id;
        this.name = name;
        this.count = count;
        this.seq = seq;
        this.sortType = sortType;
        this.pointer = pointer;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getCount() {
        return count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    public Integer getSeq() {
        return seq;
    }

    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    public Integer getSortType() {
        return sortType;
    }

    public void setSortType(Integer sortType) {
        this.sortType = sortType;
    }

    public Integer getPointer() {
        return pointer;
    }

    public void setPointer(Integer pointer) {
        this.pointer = pointer;
    }

}
