package com.d.dmusic.module.greendao.music;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.d.dmusic.module.greendao.music.base.MusicModel;

/**
 * Entity mapped to table "LOCAL_ALL_MUSIC".
 */
public class LocalAllMusic extends MusicModel {

    public LocalAllMusic() {
    }

    public LocalAllMusic(String url) {
        this.url = url;
    }

    public LocalAllMusic(String url, String songName, String singer, String album, Long duration, Long size, String filePostfix, String folder, String lrcName, String lrcUrl, Boolean isCollected, Integer seq, Long timeStamp) {
        super(url, songName, singer, album, duration, size, filePostfix, folder, lrcName, lrcUrl, isCollected, seq, timeStamp);
    }
}